### PR TITLE
Add orca files to the qforce_examples

### PR DESCRIPTION
**Pull request by xiki-tempula**
I have tried to make this repo into a project that will hold examples as well as host file that could be used for the tests in the Qforce. This is a rather large change and please tell me if there is something that you don't like. The overall structure is generated with cookie-cutter like pycolt.

- Moved examples into qforce_examples folder.
- Make the qforce_examples installable such that it could be installed to test qforce.
- Allow the files to be accessed from qforce_examples module as a dictionary.
- Make a simple test that will check the existence of these file.

### CODE REVIEW

**Comment by xiki-tempula** [comment]
@selimsami Sorry, I know this probably brings too much change to the example.
I'm interested in fixing https://github.com/selimsami/qforce/issues/15 and think it will be very helpful if one could test the implementation. I wonder what is your feeling about this PR? 
I saw that you are setting the versions manually so I guess you might not like versionner. I could remove versionner if you don't like it.

**Comment by selimsami** [comment]
I really like the changes as a whole, but I did not have time to do a detailed review yet.
Working on a grant application with a deadline next week. Will have much more free time after that...
Could you maybe turn this PR into a branch? Then I could also make changes as needed.

Improving the testing and maybe adding some CI to Q-Force is on my to-do list, and this seems like a nice start for it.

**Comment by xiki-tempula** [comment]
@selimsami Certainly no rush. 
I _think_ I have granted your access right to this branch so you _should_ be able to edit it now.

**Comment by selimsami** [comment]
I have some review for this PR:

**Repository updates:**
- I would remove versioneer, this is probably not necessary for an examples repository.
- I would keep qforce_examples directory free of python if possible (tests, datafiles.py, _version.py, __init__.py). Perhaps the necessary ones could be moved do a different directory?
- Could you explain why the devtools directory is needed for this repository? Ideally would prefer to skip this.
- Summary: I like this repo as simple as possible with minimal/no code to make it not confusing for the first-time user. I understand it has to be installable for the tests but my preference is that it only the minimal required stuff needed to be installed and nothing more. Open to discussion of course.


**ORCA examples:**
- You put the files in the default_settings directory, but have many non-default settings. I would only have software=orca in the settings or use instead custom_settings directory.
- Necessary files should be put in the necessary_files directory, similar to other software and not in propane_qforce.
- Fragment files have ~2. This should be changed to ~1, else it will not work for the tester.

**Comment by xiki-tempula** [comment]
@selimsami Thanks for the review.

Repository updates:

> I would remove versioneer, this is probably not necessary for an examples repository.

I will remove it.

> I would keep qforce_examples directory free of python if possible (tests, datafiles.py, _version.py, init.py). Perhaps the necessary ones could be moved do a different directory?

Sure. We could have `qforce_examples` which is just for the files and `qforce_examples_src` for the py file such that it could be installed. @selimsami Would you comment on the naming? Thanks.

> Could you explain why the devtools directory is needed for this repository? Ideally would prefer to skip this.

So I was thinking that there will be CI for the qforce_examples repo as well and devtools are there to help the CI work. Obviously, CI is need for some repo where there are hundreds of data files but for qforce_examples it might be too much and we can ignore it.

> Summary: I like this repo as simple as possible with minimal/no code to make it not confusing for the first-time user. I understand it has to be installable for the tests but my preference is that it only the minimal required stuff needed to be installed and nothing more. Open to discussion of course.

I agree.

ORCA examples:

> You put the files in the default_settings directory, but have many non-default settings. I would only have software=orca in the settings or use instead custom_settings directory.

I was still working on the ORCA when I made this PR, I will change it.

> Necessary files should be put in the necessary_files directory, similar to other software and not in propane_qforce.

I have some questions with regard to this. So, I was thinking that the user should be able to look at the examples and compare their own files with the examples. So it would be nice if they have the same file structure.
It might cause confusion if they see the fragments in their own fragments directory but is in the same directory as the hessian calculation in the examples.

> Fragment files have ~2. This should be changed to ~1, else it will not work for the tester.

This is a bit weird, I will have a look.

**Comment by selimsami** [comment]
> Sure. We could have qforce_examples which is just for the files and qforce_examples_src for the py file such that it could be installed. @selimsami Would you comment on the naming? Thanks.

How about just src? 

> So I was thinking that there will be CI for the qforce_examples repo as well and devtools are there to help the CI work. Obviously, CI is need for some repo where there are hundreds of data files but for qforce_examples it might be too much and we can ignore it.

Perhaps we can keep it out until we do have some CI in place. And I'd be more interested to start with CI on the main qforce repo :) that one is a bit more urgent I think.

> I have some questions with regard to this. So, I was thinking that the user should be able to look at the examples and compare their own files with the examples. So it would be nice if they have the same file structure.
It might cause confusion if they see the fragments in their own fragments directory but is in the same directory as the hessian calculation in the examples.

I agree. We could make a subdirectory in necessary_files called fragments and put the fragment data in there. The necessary_files are needed so the users get to experience the 3 stages of the qforce run (in line with the [tutorial](https://qforce.readthedocs.io/en/latest/examples.html)). If all the files are in propane_qforce, only the last phase will be experienced.

> This is a bit weird, I will have a look.

Not too weird: You probably had a different setting beforehand, which took ~1.

**Comment by xiki-tempula** [comment]
@selimsami Thanks for the review.

I have set the directory structure to
```
default_settings/
    necessary_files/
        fragments/
            CC_H8C3_d91b46644317dee9c2b868166c66a18c~1.log
        propane_hessian.log
    propane.xyz
    settings
```
and apply the same structure to all of the examples.

I have moved the py scripts to src and removed all the py files from the examples.
However, I found it very difficult to include the data files in the distribution (there might be a way of doing it but I don't know).
Usually, one could easily include the data files inside the package folder which in this case is `src`. However, I don't know how to include the folders outside the package folder.

**Comment by selimsami** [comment]
does it work now? or shall I have a look if there is an alternative?

**Comment by xiki-tempula** [comment]
@selimsami No I cannot get it to work. I wonder if you can have a look at the setup.py to see how to include the examples in the distribution.

**Comment by selimsami** [comment]
Okay I also had trouble making this work. The simplest solution I could come up with is the following structure:

```
qforce_examples/
    __init__.py (in here goes what you have in datafiles.py)
    gaussian
    qchem
    orca
```

If one day we need more code in here, two options I see:

```
examples/
    __init__.py
    gaussian/
    qchem/
    orca/
src/
    code1.py
    code2.py
```

or 

```
qforce_examples/
    __init__.py
    gaussian/
    qchem/
    orca/
    src/
        code1.py
        code2.py
```

**Comment by xiki-tempula** [comment]
I will make it structured like this.
```
qforce_examples/
    __init__.py (in here goes what you have in datafiles.py)
    gaussian
    qchem
    orca
```

**Comment by xiki-tempula** [comment]
@selimsami I think it looks good to me now.

**Comment by selimsami** [comment]
Looks great, thanks a lot!

**Pull request merged**
